const Keyv = require("keyv");
global.fs = require('fs');
global.db = new Keyv('sqlite://database.sqlite');
global.path = require('path');
global.encrypt = require('./encrypt.js')
global.app = require('../modules/server.js')();
global.core = require('./core.js')
global.WebSocket = require('ws')
global.next = require('next')
